### PR TITLE
Propagate headers only if explicitly asked

### PR DESCRIPTION
**Pull request by jettify**

### CODE REVIEW

**Comment by adriancole** [comment]
Curious about motivation? If anything usually we are trying to get tools to propagate, not *not* propagate. Consitent ids even when unsampled allows use cases such as log correlation and "firehose mode" where you dump

**Comment by adriancole** [comment]
.. 100% into another system (even if not logs)

**Comment by jettify** [comment]
Principle of least astonishment, in rare cases extra header may have unexpected side effect, but if other libraries do this we should too. Will create PR to change default value.

**Comment by jettify** [comment]
Fixed in https://github.com/aio-libs/aiozipkin/pull/54

**Pull request merged**
